package com.neta.teman.dawai.api;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.neta.teman.dawai.api.applications.base.ServiceResolver;
import com.neta.teman.dawai.api.models.dao.User;
import com.neta.teman.dawai.api.services.FileService;
import com.neta.teman.dawai.api.services.UserService;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.TestPropertySource;

@SpringBootTest
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestPropertySource(locations = "classpath:test.properties")
public class UploadTests {

    Logger log = LoggerFactory.getLogger(getClass());

    @Autowired
    FileStorageService fileStorageService;

    @Test
    void auth() throws JsonProcessingException {
        String pdf = "JVBERi0xLjQKJeLjz9MKNCAwIG9iago8PC9GaWx0ZXIvRmxhdGVEZWNvZGUvTGVuZ3RoIDU1NT4+c3RyZWFtCoSHlon3Ll7W5WyuyRViPtJClpoVCOw+MOfNwVDFEyZde7w88/cyD0II6ZwRhzIuyyRaCFxwno/S6HFj/2k0W6qkZdmP0fMtcjzy75JiORKNoh6F4TBf4Fo0PHjG6R0qz9KZDYO3MJl8h27s+7I8TXNLx2iinuB/feeoCGlv7xlNfpwjdpfw+az2sIc2iMMoH06+6wsOuYuIVsz9he8MVmqZYK99rUMpCKXSInFtxymAwAvdihoDBL9uuTUGMYsIcVqRRWY5xiAy6HvfpQOvQmku6FJvPhqpfJ2VtFEaW/lfRS9aRIvz9iLW6bXURdHIMAz157AwmG92T/7U2OgrrhgS1XhYeXv4GcOXxZ+kqdrhpe1bKhBGowJVCPvAfo1Cyz4KqLApVr6JLTRAtWruHT2X/lrDBRT9ZY1E5Hs5hPD1fG8CotRWKbg/RRqKNmwjnUFL24hVisYlP+bjIrq3yQRi2qhdFxko4EcgINcBs9I1SXSHxz6FqfzfBTTpEJQnH5h7CZK+M/jYK35Pf/RY06RqvK6ju+BkT63nslxfbV9A7yIE+BRObUewVWDPDHihZoKazYWs+qEhvRvppzqggrlPd7nYp4QttKJr/IGGzsTt2xf6+NjxAUIqS94o17Yo+lGDjLkSyrZC4JToEptKRSK640GLIh/FtYlI1gOg5A3YS2fbjsPHT2a348ViGxGh/o8og/zThkS3iAwXMWzZmc/yIHkcBiU/vJsRSwplbmRzdHJlYW0KZW5kb2JqCjEgMCBvYmoKPDwvVGFicy9TL0dyb3VwPDwvUy9UcmFuc3BhcmVuY3kvVHlwZS9Hcm91cC9DUy9EZXZpY2VSR0I+Pi9Db250ZW50cyA0IDAgUi9UeXBlL1BhZ2UvUmVzb3VyY2VzPDwvQ29sb3JTcGFjZTw8L0NTL0RldmljZVJHQj4+L1Byb2NTZXQgWy9QREYgL1RleHQgL0ltYWdlQiAvSW1hZ2VDIC9JbWFnZUldL0ZvbnQ8PC9GMSAyIDAgUi9GMiAzIDAgUj4+Pj4vUGFyZW50IDUgMCBSL01lZGlhQm94WzAgMCA1OTUgODQyXT4+CmVuZG9iago2IDAgb2JqClsxIDAgUi9YWVogMCA4NTIgMF0KZW5kb2JqCjIgMCBvYmoKPDwvU3VidHlwZS9UeXBlMS9UeXBlL0ZvbnQvQmFzZUZvbnQvSGVsdmV0aWNhL0VuY29kaW5nL1dpbkFuc2lFbmNvZGluZz4+CmVuZG9iagozIDAgb2JqCjw8L1N1YnR5cGUvVHlwZTEvVHlwZS9Gb250L0Jhc2VGb250L0hlbHZldGljYS1Cb2xkL0VuY29kaW5nL1dpbkFuc2lFbmNvZGluZz4+CmVuZG9iago1IDAgb2JqCjw8L0tpZHNbMSAwIFJdL1R5cGUvUGFnZXMvQ291bnQgMS9JVFhUKNXU8MgnKT4+CmVuZG9iago3IDAgb2JqCjw8L05hbWVzWyhvel99UT5ZnnoSpVpbR16lJMQpIDYgMCBSXT4+CmVuZG9iago4IDAgb2JqCjw8L0Rlc3RzIDcgMCBSPj4KZW5kb2JqCjkgMCBvYmoKPDwvTmFtZXMgOCAwIFIvVHlwZS9DYXRhbG9nL1BhZ2VzIDUgMCBSL1ZpZXdlclByZWZlcmVuY2VzPDwvUHJpbnRTY2FsaW5nL0FwcERlZmF1bHQ+Pj4+CmVuZG9iagoxMCAwIG9iago8PC9Nb2REYXRlKHS0V/WWjZXg6qSqv2eFgsdKBy8mUXGMKS9DcmVhdG9yKHrvFrXBz/a0qvLo/yaQ+pkDRXlzGGHdvIj3WMIzY9RbomLW44ACWPyOaRtcdFwpleo9nWjpkkksuzKsWzLzni3/Yqw3GYTllTa4zvdotL0pL0NyZWF0aW9uRGF0ZSh0tFf1lo2V4Oqkqr9nhYLHSgcvJlFxjCkvUHJvZHVjZXIoWdoAvdCdlv/rs62rN8mWwTUEQFUpL0F1dGhvcihk61xipMqd4LCt/PMpPj4KZW5kb2JqCjExIDAgb2JqCjw8L08gKN7/XZ8b7B3+5TP9exhLH+OGBjKXLXWIJyWtdsWAtJZUKS9QIC02MC9SIDIvRmlsdGVyL1N0YW5kYXJkL1UgKNB6+aZZEgJdrEpQSH1U0EoG2ETtnVx09zbu8Vrd0Vxi+GgpL1YgMT4+CmVuZG9iagp4cmVmCjAgMTIKMDAwMDAwMDAwMCA2NTUzNSBmIAowMDAwMDAwNjM3IDAwMDAwIG4gCjAwMDAwMDA5MjIgMDAwMDAgbiAKMDAwMDAwMTAxMCAwMDAwMCBuIAowMDAwMDAwMDE1IDAwMDAwIG4gCjAwMDAwMDExMDMgMDAwMDAgbiAKMDAwMDAwMDg4NyAwMDAwMCBuIAowMDAwMDAxMTY2IDAwMDAwIG4gCjAwMDAwMDEyMjAgMDAwMDAgbiAKMDAwMDAwMTI1MiAwMDAwMCBuIAowMDAwMDAxMzU1IDAwMDAwIG4gCjAwMDAwMDE1ODggMDAwMDAgbiAKdHJhaWxlcgo8PC9JbmZvIDEwIDAgUi9FbmNyeXB0IDExIDAgUi9JRCBbPDJmZTM4NmRkYTRjYTU0MjQzY2Q2YzIxYTAzODU1YmU5Pjw0N2VjMjkxOTYzMzJjYjVhODA5MzYzYWUzOTdhODEzZj5dL1Jvb3QgOSAwIFIvU2l6ZSAxMj4+CnN0YXJ0eHJlZgoxNzE1CiUlRU9GCg==";
        fileStorageService.storeFile("196406241987032001", pdf, "pdf");
    }


}
